name: C/C++ CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get install csh clang-format
    - name: setup
      run: cd tools; make bats.done cpplint.done sptk.done
    - name: make
      run: make
    - name: make format
      run: make format
    - name: make test
      run: make test
