name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  ubuntu-latest:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install csh parallel valgrind libpcre3-dev

      - name: Tool
        run: cd tools && make cppcheck.done
